# IMPORTANTE, SI NO, NO FUNCIONA NAIPE.

# NOMBRE
spring.application.name=gameapi
# HABILITA EL H2 = TRUE
spring.h2.console.enabled=true
# PATH PA ENTRAR A LA CONSOLA H2
spring.h2.console.path=/h2-console
# URL DE LA BD EN MEMORIA(MEM)
spring.datasource.url=jdbc:h2:mem:gamesdb
# DRIVER DE H2
spring.datasource.driver-class-name=org.h2.Driver
# USERNAME DE LA BD
spring.datasource.username=sa
# PASSWORD DE LA BD, EN ESTE CASO VACIA POR DEFECTO
spring.datasource.password=
# CREA Y ELIMINA LA TABLA AL INICIAR Y CERRAR LA APP
spring.jpa.hibernate.ddl-auto=create-drop
# MUESTRA LAS CONSULTAS SQL EN LA CONSOLA
spring.jpa.show-sql=true