spring.application.name=demoinsforge
server.port=8080
# Conexion con insForge
spring.datasource.url=jdbc:postgresql:*HOST*:5432/*DB*?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=301cc6a4d9851e9690cc0a089f37906d
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurar JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Caracteristicas de conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# Opcional: schema por defecto si lo necesitas
spring.jpa.properties.hibernate.default_schema=public