spring.application.name=swagger
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=create

# Ruta Swagger
springdoc.swagger-ui.path=/swagger

# Ruta OpenAPI JSON
springdoc.api-docs.path=/api-docs